apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  labels:
    app: elasticsearch
    version: "5.6.2"
    role: data
spec:
  serviceName: els-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
        version: "5.6.2"
        role: data
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values: 
                - data
            topologyKey: kubernetes.io/hostname
      containers:
      - name: elasticsearch-data
        securityContext:
          privileged: true
        image: [REGISTRY-URL]/elasticsearch:5.6.2
        imagePullPolicy: Always
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: NODE_NAME
          value: "${NODENAME}.els-headless.default.svc.cluster.local"
        - name: NETWORK_HOST
          value: "${NODENAME}.els-headless.default.svc.cluster.local"
        - name: HTTP_ENABLE
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_MASTER
          value: "false"          
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-master-0.els-headless.default.svc.cluster.local,elasticsearch-master-1.els-headless.default.svc.cluster.local,elasticsearch-master-2.els-headless.default.svc.cluster.local"
        resources:
          limits:
            cpu: 1000m
            memory: 4096Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 9300
          name: data-tcp
          protocol: TCP
        - containerPort: 9200
          name: data-http
          protocol: TCP
        volumeMounts:
        - mountPath: /home/elasticsearch/elasticsearch/data
          name: data
      volumes:
      - name: data
        hostPath:
         path: /data/elasticsearch/elasticsearch/data            
