apiVersion: v1
kind: Service
metadata:
  name: els-headless
  labels:
    product: els-headless
spec:
  ports:
  - port: 9200
    name: server
  - port: 9300
    name: client
  clusterIP: None
  selector:
    product: elasticsearch
