apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    product: elasticsearch
    version: "5.5.0"
spec:
  serviceName: els-headless
  replicas: 3
  template:
    metadata:
      labels:
        product: elasticsearch
        version: "5.5.0"
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: product
                operator: In
                values: 
                - elasticsearch
            topologyKey: kubernetes.io/hostname
      containers:
      - name: elasticsearch
        securityContext:
          privileged: true
        image: [REGISTRY-URL]/elasticsearch:5.5.0
        imagePullPolicy: Always
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-0.els-headless.default.svc.kubernetes,elasticsearch-1.els-headless.default.svc.kubernetes,elasticsearch-2.els-headless.default.svc.kubernetes"
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 10Mi
