apiVersion: v1
kind: Service
metadata:
  name: els-headless
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: tcp
  clusterIP: None
  selector:
    app: elasticsearch
    role: master
